services:
  - type: web
    name: pricetracker-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DB_HOST
        value: "" 
      - key: DB_NAME
        value: "" 
      - key: DB_USER
        value: "" 
      - key: DB_PASSWORD
        value: "" 
      - key: BACKEND_URL
        value: "" # Tu URL de Render (https://...)
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""
      - key: SESSION_SECRET
        value: "" # Genera una cadena aleatoria
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHON_VERSION
        value: 3.11.0
