services:
  - type: web
    name: pricetracker-pro
    env: python
    # Instalamos dependencias del backend
    buildCommand: pip install -r backend/requirements.txt
    # Arrancamos con uvicorn (el frontend se sirve desde FastAPI)
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: precios-db # Esto asume que crear√°s una DB en Render llamada precios-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
